apiVersion: v1
# membuat pvc
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: dicoding
  labels:
    app: mongo-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      # sebesar 5Gi
      storage: 5Gi
