apiVersion: v1
# membuat service
kind: Service
metadata:
  # dengan nama mongo-service, ns dicoding
  labels:
    name: mongo
  name: mongo-service
  namespace: dicoding
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  # port nodeport 30002, internal 27017
  - name: 27017app
    nodePort: 30002
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    # mengarah ke pods mongo
    app: mongo
  sessionAffinity: None
  # tipe nodeport
  type: NodePort
status:
  loadBalancer: {}
