apiVersion: v1
# membuat service
kind: Service
metadata:
  # dengan nama order-service, di ns dicoding
  labels:
    name: order-service
  name: order-service
  namespace: dicoding2
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  # nodeport 30000 dan diakses 3000 di internal
  ports:
  - name: 3000app
    nodePort: 30000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    # mengarah ke pod order-service
    name: order-service
  sessionAffinity: None
  # tipe nodeport
  type: NodePort
status:
  loadBalancer: {}
