apiVersion: apps/v1
# membuat deployment
kind: Deployment
metadata:
  # menggunakan label dan nama order-service di deploy di namespace dicoding2
  labels:
    name: order-service
  name: order-service
  namespace: dicoding2
spec:
  # di deploy dengan 1 replika
  replicas: 1
  selector:
    matchLabels:
      name: order-service
  template:
    metadata:
      labels:
        name: order-service
    spec:
      # menggunakan 1 container dengan nama order-service, image diambil dari github container registry milik man20820
      containers:
      - name: order-service
        image: ghcr.io/man20820/order-service:latest
        ports:
        # port container 3000 TCP
        - containerPort: 3000
          protocol: TCP
          # limit cpu & memory
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
            # env dari aplikasi
        env:
        - name: PORT
          value: "3000"
        - name: AMQP_URL
          value: "amqp://my-release-rabbitmq.default.svc.cluster.local:5672"

